### ISSUE TITLE
The Calendar, Clock and Volume icons aren't showing

### ISSUE THREAD

**Issue by dm699** [Sinomor/dotfiles#1]
![](https://i.imgur.com/dj9Tn5K.png)

**Comment by Sinomor** [comment]
have you installed both feather fonts? And what about other fonts with icons, have you something?

**Comment by dm699** [comment]
> have you installed both feather fonts? And what about other fonts with icons, have you something?

Yes I did install feather fonts what other fonts/icons do I have to install?

**Comment by Sinomor** [comment]
> > have you installed both feather fonts? And what about other fonts with icons, have you something?
> 
> Yes I did install feather fonts what other fonts/icons do I have to install?

You need to remove ALL other fonts with icons, material design, for example

**Comment by dm699** [comment]
> > > have you installed both feather fonts? And what about other fonts with icons, have you something?
> > 
> > 
> > Yes I did install feather fonts what other fonts/icons do I have to install?
> 
> You need to remove ALL other fonts with icons, material design, for example

Oh, thank you very much 
It worked
