### ISSUE TITLE
Wifi backend

### ISSUE THREAD

**Issue by LeVraiArdox** [Sinomor/dotfiles#3]
Hi there. Just wanted to ask what wifi manager do you use. Is it iwd or NetworkManager ? thanks :+1:

**Comment by Sinomor** [comment]
> Hi there. Just wanted to ask what wifi manager do you use. Is it iwd or NetworkManager ? thanks :+1: 

Of course i use networkmanager. It have needed functionality for network applet, also i copy the network applet from myagko dotfiles

**Comment by LeVraiArdox** [comment]
Oh, i see thanks !

And how does the wifi menu is supposed to work ? i tried to add it to my rice but the networks aren't shown on the menu, which is pretty strange, since the code looks ok to me...
I can send the file if you have time to investigate.

**Comment by Sinomor** [comment]
> networks aren't shown

What distro you use now?

**Comment by LeVraiArdox** [comment]
I use Arch btw

**Comment by Sinomor** [comment]
> I use Arch btw 

Did you install networkmanager and enable service?

**Comment by LeVraiArdox** [comment]
Sure, i couldn't use the network without
