### ISSUE TITLE
What Icon Font Includes The Memory Icon?

### ISSUE THREAD

**Issue by VehementHam** [Sinomor/dotfiles#4]
The memory icon is not on https://feathericons.com/

**Comment by zrchx** [comment]
try nerd fonts or maybe material

**Comment by Sinomor** [comment]
https://github.com/Sinomor/dotfiles/tree/main/home%2F.fonts ............

**Comment by VehementHam** [comment]
Yeah, but which file is it, and where did you find it?

**Comment by Sinomor** [comment]
> Yeah, but which file is it, and where did you find it?

I got the fonts from [myagko](https://github.com/Myagko/dotfiles) rice. So, [click](https://github.com/myagko/dotfiles/blob/main/home/.fonts/feather_font_revamp.ttf) to get him version of fonts

**Comment by VehementHam** [comment]
Alright, I filed an issue on his git. How come your fonts are in 2 files, and his is in 1?

**Comment by VehementHam** [comment]
`feather-font-addon` is the one, I tested it out. How did you come across this file? Is this the feather-font-revamp file with a different name? Are you 100% sure that this is open source?

**Comment by Sinomor** [comment]
> Alright, I filed an issue on his git. How come your fonts are in 2 files, and his is in 1?

He updated a font nearly month ago, but I'm not update this, maybe I'm will do this late...

**Comment by VehementHam** [comment]
Yeah, he removed his commit history :disappointed:

**Comment by VehementHam** [comment]
https://github.com/myagko/dotfiles/issues/1#issuecomment-1826878138
